version: '3'

tasks:
  hello:
    cmds:
      - echo "Hello from task"

  rebuild:
    cmds:
      - sudo nixos-rebuild switch

  cleanup:
    cmds:
      - sudo nix-env --delete-generations +5 --profile /nix/var/nix/profiles/system
      - sudo nix-store --gc

  test:
    cmds:
      - sudo nixos-rebuild dry-build

  update:
    cmds:
      - sudo nix-channel --update
      - task: rebuild